# Generated by Django 2.2.1 on 2019-06-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartscache',
            options={},
        ),
    ]
