# Generated by Django 2.2.1 on 2019-06-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190603_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowplaying',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nowplaying', to='core.Artist'),
        ),
        migrations.AlterField(
            model_name='nowplaying',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nowplaying', to='core.Track'),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrobbles', to='core.Artist'),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrobbles', to='core.Track'),
        ),
    ]
