# Generated by Django 2.2.1 on 2019-06-02 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scrobble_server.api.v12.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_version', models.CharField(max_length=255)),
                ('banned', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('client_id', 'client_version')},
            },
        ),
        migrations.CreateModel(
            name='ScrobbleSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=scrobble_server.api.v12.models.make_session_key, max_length=32)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobble_sessions', to='v12.Client')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobble_sessions', to='core.Profile')),
            ],
            options={
                'ordering': ['-created'],
                'default_related_name': 'scrobble_sessions',
            },
        ),
        migrations.CreateModel(
            name='MD5AuthHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='md5hash', to='core.Profile')),
            ],
        ),
        migrations.AddIndex(
            model_name='scrobblesession',
            index=models.Index(fields=['key'], name='v12_scrobbl_key_a675f0_idx'),
        ),
    ]
